EBC.BuscaInsumo.Mvc/Areas/DoMyRecipe/Models/RecipeViewModel.cs
using EBC.BuscaInsumo.Mvc.Areas.DoMyRecipe.Domain.Objects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EBC.BuscaInsumo.Mvc.Areas.DoMyRecipe.Models {
	public class RecipeViewModel {


		public string SelectedStyle { get; set; }
		public List<Style> Styles { get; set; }

		public List<Grain> Grains { get; set; }

	}
}

EBC.BuscaInsumo.Mvc/ViewModels/SearchViewModel.cs
using EBC.BuscaInsumo.Mvc.Services.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EBC.BuscaInsumo.Mvc.ViewModels {
	public class SearchViewModel {
		public IEnumerable<ProductModel> model { get; set; }
		public string terms { get; set; }
	}
}

EBC.BuscaInsumo.Mvc/Areas/DoMyRecipe/Controllers/HomeController.cs
using EBC.BuscaInsumo.Mvc.Areas.DoMyRecipe.Domain.Objects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EBC.BuscaInsumo.Mvc.Areas.DoMyRecipe.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /DoMyRecipe/Home/

        public ActionResult Index()
        {
            return View();
        }

		public ActionResult New() {

			IList<Style> styles = DoMyRecipe.Domain.DoMyRecipeApi.GetAllStyles();

			return View(styles);
		}
    }
}

EBC.BuscaInsumo.Mvc/Areas/DoMyRecipe/Controllers/RecipeController.cs
using EBC.BuscaInsumo.Mvc.Areas.DoMyRecipe.Domain;
using EBC.BuscaInsumo.Mvc.Areas.DoMyRecipe.Domain.Collections;
using EBC.BuscaInsumo.Mvc.Areas.DoMyRecipe.Domain.Objects;
using EBC.BuscaInsumo.Mvc.Areas.DoMyRecipe.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace EBC.BuscaInsumo.Mvc.Areas.DoMyRecipe.Controllers {
	public class RecipeController : Controller {
		//
		// GET: /DoMyRecipe/Recipe/

		public ActionResult Index() {
			RecipeViewModel viewModel = new RecipeViewModel() {
				Styles = DoMyRecipeApi.GetAllStyles(),
				Grains = DoMyRecipeApi.GetAllGrains()
			};

			return View(viewModel);
		}


		public JsonResult GetSelectedStyle(int id) {

			Style style = DoMyRecipeApi.GetAllStyles().Find(obj => obj.Id.Equals(id));

			return Json(style, JsonRequestBehavior.AllowGet);
		}

		public JsonResult SearchGrain(string name) {
			return Json(DoMyRecipeApi.SearchGrains(name), JsonRequestBehavior.AllowGet);
		}
	}
}

EBC.BuscaInsumo.Mvc/Controllers/HomeController.cs
using EBC.BuscaInsumo.Mvc.Services;
using EBC.BuscaInsumo.Mvc.Services.Models;
using EBC.BuscaInsumo.Mvc.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EBC.BuscaInsumo.Mvc.Controllers {
	public class HomeController : Controller {
		//
		// GET: /Home/

		public ActionResult Index() {
			return View();
		}

		[HttpPost]
		public ActionResult Search(string terms) {

			List<ProductModel> products = ProductService.GetProductsFromSearch(terms);

			SearchViewModel model = new SearchViewModel() { model = products, terms = terms };

			if (products.Count.Equals(0))
				return View("NoResults", model);

			return View(model);
		}

	}
}

EBC.BuscaInsumo.Mvc/Areas/DoMyRecipe/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "../Shared/_Layout.cshtml";
}

<h2>Index</h2>
@Html.ActionLink("Nova Receita", "Index", "Recipe")

EBC.BuscaInsumo.Mvc/Areas/DoMyRecipe/Views/Recipe/Index.cshtml
@model EBC.BuscaInsumo.Mvc.Areas.DoMyRecipe.Models.RecipeViewModel
@{
	ViewBag.Title = "Index";
	Layout = "../Shared/_Layout.cshtml";
}

@*<style type="text/css">
		.unselectedGrain {
			background-color: #ffffff;
		}

		.selectedGrain {
			background-color: #000000;
		}
	</style>*@

<style>
	#feedback {
		font-size: 1.4em;
	}

	#selectable .ui-selecting {
		background: #FECA40;
	}

	#selectable .ui-selected {
		background: #F39814;
		color: white;
	}

	#selectable {
		list-style-type: none;
		margin: 0;
		padding: 0;
		width: 60%;
	}

		#selectable li {
			margin: 3px;
			padding: 0.4em;
			font-size: 1.4em;
			height: 18px;
		}
</style>

<script type="text/javascript" language="javascript">

	function callSearchGrain(value) {

		$.ajax({
			url: "http://localhost/EBC.BuscaInsumo.Mvc/DoMyRecipe/Recipe/SearchGrain",
			data: { name: value },
			dataType: "json",
			method: "GET"
		}).done(function (obj) {
			$("#grainSearchResult").html("");
			for (var i = 0; i < obj.length; i++) {
				$("#grainSearchResult").append(createElementResultSearchGrain(obj[i].Id, obj[i].Name, obj[i].Notes));
			}
		}).error(function (obj) {

		});
	}

	function createElementResultSearchGrain(id, name, notes) {
		// onclick='javascript:onclickSearchResult(this);'
		// class='unselectedGrain'
		// selectedGrain='false'
		return "<div grainId=" + id + " id='grain" + id + "' class='ui-widget-content'>" + name + "<br/><div style='font-size:smaller'>" + notes + "</div></div>";
	}

	function isArrowKey(keyCode) {
		return (keyCode.keyCode === 38 || keyCode.keyCode === 40)
	}



	function onclickSearchResult(obj) {
		$("div [id^=grain]").removeClass("selectedGrain");
		if ($(obj).attr("selectedGrain") === "false") {
			$(obj).attr("selectedGrain", "true");
			$(obj).removeClass("unselectedGrain");
			$(obj).addClass("selectedGrain");
		} else {
			$(obj).attr("selectedGrain", "false");
			$(obj).removeClass("selectedGrain");
			$(obj).addClass("unselectedGrain");
		}
	}

	$(document).ready(function () {

		$("#style").change(function () {

			$.ajax({
				url: "http://localhost/EBC.BuscaInsumo.Mvc/DoMyRecipe/Recipe/GetSelectedStyle",
				data: { id: $(this).val() },
				dataType: "json",
				method: "GET"
			}).done(function (obj) {

			}).error(function (obj) {

			});
		});

		$("#grainSearch").keyup(function (keyCode) {

			//if (isArrowKey(keyCode)) {
			//} else {
			callSearchGrain($(this).val());
			//}

			$("#grainSearchResult").selectable({
				stop: function () {
					var result = $("#select-result").empty();
					$(".ui-selected", this).each(function () {
						var index = $("#selectable div").index(this);
						result.append(" #" + (index + 1));
					});
				}
			});

		});


	});

</script>

<h2>Nova Receita</h2>

<select id="style">
	<option value="0">Select</option>
	@foreach (EBC.BuscaInsumo.Mvc.Areas.DoMyRecipe.Domain.Objects.Style style in @Model.Styles) {
		<option value="@style.Id">@style.Name</option>
	}
</select>


<br />
<div>
	<span id="select-result">none</span>
	<input type="text" id="grainSearch" /><br />
	<div id="grainSearchResult">


	</div>
</div>

EBC.BuscaInsumo.Mvc/Areas/DoMyRecipe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	@Styles.Render("~/Content/css/Site.css")
	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/jqueryui")
	
</head>
<body>
	@RenderBody()

	
	@RenderSection("scripts", required: false)

	
</body>

</html>

EBC.BuscaInsumo.Mvc/Views/Home/Index.cshtml
@{
	ViewBag.Title = "Busca Insumo";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="searchContainer" style="width: 100%; padding-top: 120px;">
	<div style=" text-align: center; width:inherit;">

		<h2>O que voce procura para sua cerveja ?</h2>

		@using (Html.BeginForm("Search", "Home", FormMethod.Post)) {

			@Html.TextBox("terms", null, new { style = "width:80%" })
			<input type="submit" id="searchButton" value="Buscar Insumos" />
			
		}

		
		
	</div>
</div>

EBC.BuscaInsumo.Mvc/Views/Home/NoResults.cshtml
@model EBC.BuscaInsumo.Mvc.ViewModels.SearchViewModel
@{
	ViewBag.Title = "NoResults";
	Layout = "~/Views/Shared/_Layout.cshtml";
}


<div style="text-align: center; width: 100%; vertical-align: top; padding-top: 120px; ">

	<h2>O que voce procura para sua cerveja ?</h2>
	@using (Html.BeginForm("Search", "Home", FormMethod.Post)) {
		@Html.TextBoxFor(obj => obj.terms, new { style = "width:80%" })
		<input type="submit" id="searchButton" value="Buscar Insumos" />
	}

	<h3>Nenhum resultado encontrado</h3>
</div>

EBC.BuscaInsumo.Mvc/Views/Home/Search.cshtml
@model EBC.BuscaInsumo.Mvc.ViewModels.SearchViewModel


@{
	ViewBag.Title = "Search";
	Layout = "~/Views/Shared/_Layout.cshtml";
}


<div style="text-align: center; width: 100%; vertical-align: top; padding-top: 120px; ">

	<h2>O que voce procura para sua cerveja ?</h2>
	@using (Html.BeginForm("Search", "Home", FormMethod.Post)) {
		@Html.TextBoxFor(obj => obj.terms, new { style = "width:80%" })
		<input type="submit" id="searchButton" value="Buscar Insumos" />
	}


	<table style="width:100%;">
		<tr>
			<th colspan="3">
				@Model.model.Count() produtos encontrados
			</th>
		</tr>
		@foreach (var item in @Model.model) {
			<tr>
				<td align="left">

					@Html.DisplayFor(modelItem => item.name)<br />
					<span style="font-size:smaller">@item.description</span>
				</td>

				<td align="center">
					@Html.DisplayFor(modelItem => item.price)
				</td>
				<td align="left">
					<a href='@item.link' target="_blank">
						<img src='@item.image' alt="Ir para a loja" style="width:120px;">
					</a>
				</td>
				<td align="right">
					<a href='@item.link' target="_blank">
						<img src='~/Content/images/source_images/@item.logo_image' alt="Ir para a loja" style="width:120px;">
					</a>
				</td>
			</tr>
		}
	</table>


</div>

EBC.BuscaInsumo.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	@Styles.Render("~/Content/css/Site.css")
	@Scripts.Render("~/bundles/modernizr")
</head>
<body>
	@RenderBody()

	@Scripts.Render("~/bundles/jquery")
	@RenderSection("scripts", required: false)

	<div id="headerContainer" style="height: auto; width: 100%; position: fixed; top: 0; left: 0; background-color: #E9EAEC; z-index: 999;">
		<div style="width: 100%; position:relative; text-align:center; padding-bottom:15px;">
			<h3>Bem vindo ao Busca Insumos!</h3>
			<br />
			<a href="~/DoMyRecipe">
				<img src="~/Content/images/food.svg" alt="" style="width:32px; padding-right:10px;" />
			</a>
			<img src="~/Content/images/malt.svg" alt="" style="width: 32px; padding-right: 10px;" />
			<img src="~/Content/images/worms.svg" alt="" style="width:32px;" />

		</div>

	</div>
</body>

</html>